## port
server:
  port: 80

## redis
spring:
  redis:
    # 数据库索引
    database: 0
    host: 123.207.27.144
    port: 6379
    password:
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        # 最大空闲
        max-idle: 8
        # 最小空间
        min-idle: 0
    # 连接超时时间
    timeout: 10000

## logging
logging:
  config: classpath:logback-spring.xml
